### ISSUE TITLE
Broken win:azure build platform

### ISSUE THREAD

**Issue by ytausch** [conda-forge/tqdm-feedstock#127]
### Comment:

This is broken.

https://github.com/conda-forge/tqdm-feedstock/blob/13715b800a1870121b8f98ef40730bab0b50e17a/conda-forge.yml#L1

**Comment by pavelzw** [comment]
@conda-forge/tqdm

**Comment by casperdcl** [comment]
fixed by #128 methinks

**Comment by ytausch** [comment]
@casperdcl This is not fixed, your `conda-forge.yml` file is still invalid.
https://conda-forge.org/docs/maintainer/conda_forge_yml/#provider
Please reopen this issue.

In the future, conda-smithy will warn you that `win:azure` is not a recognized field name.
